# Resolve react_native_pods.rb
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.0'
prepare_react_native_project!

ENV['HERMES_ENABLED'] = '0'
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

use_frameworks! :linkage => :static

target 'wizmarketingIRN' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false
  )
end

post_install do |installer|
  # 모든 Pods의 배포 타겟을 14.0으로 강제
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end

  react_native_post_install(installer)
end
